"""add author model

Revision ID: 666764a1aa5c
Revises: fe0cfe617c8c
Create Date: 2023-03-08 15:16:02.078200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666764a1aa5c'
down_revision = 'fe0cfe617c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('author')
    # ### end Alembic commands ###
